config/routes.rb
Rails.application.routes.draw do

  root "landing#index"

  resources :books do 
    resources :messages
  end  

  resources :users do 
    resources :messages
  end  

  resources :users do
    resources :favorites
  end  

  resources :landing

  get "/log-in" => "sessions#new"   

  post "/log-in" => "sessions#create"

  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :user_books
  has_many :users, through: :user_books
  has_many :messages
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :title, :review, presence: true
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  has_many :books, through: :user_books
  has_many :messages
  has_many :user_books
  has_many :favorites

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(name,password)  
    user = User.where(name: name).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end    
  end

end

app/models/user_book.rb
class UserBook < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/users_books.rb
class UsersBooks < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_filter :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
  end  

  def create
    @book = Book.find_by(book_id: params[:book][:book_id]) || Book.create(book_params)
    render :json => @book     
  end  

  def show
    @book = Book.find_by(book_id: params[:id])
  end  

  def edit
    @book = Book.find(params[:id])
  end  

  def update
    binding.pry

    oldRating = params[:oldRating].to_f
    newRating = params[:newRating].to_f
    count = params[:count].to_f
    rating = ((oldRating*count)+newRating)/(count+1)
    rating = rating.round(2)

    @book = Book.find_by(book_id: params[:book_id])
    if @book.try(:ratingCount)
      @book.update(ratingCount: @book.ratingCount + 1)
    else  
      @book.update(ratingCount: count.to_i+1)
      @book.update(rating: rating);
    end  
    
  end 

  def destroy
    @book = Book.delete(params["id"])
    redirect_to "/books"
  end 

  private
  def book_params
    if current_user
      params[:user_id] = current_user.id.to_s
      @book = params.require(:book).permit(:book_id, :user_id)
    else   
      @book = params.require(:book).permit(:book_id)
    end  
  end 

  def book_edit_params
    @book = params.require(:book).permit(:rating)
  end 

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = Favorite.all
  end  

  def create
    binding.pry
    bookId = params[:favorite][:book_id]

    if Book.where(:book_id => bookId).blank?
      @book = Book.create(book_params)  
    end 

    if Favorite.where(:book_id => bookId).blank?
      @favorite = Favorite.create(favorite_params);
    else
      @favorite = Favorite.find_by(book_id: bookId)      
    end  

    redirect_to "/users/#{@favorite.user_id}/messages"
  end  

  def show
    @favorites = Favorite.find(params[:id])
  end  

  def favorite_params
    params.require(:favorite).permit(:book_id,:user_id,:title,:img)
  end  

  def book_params
    if current_user
      params[:book][:user_id] = current_user.id
    end  
    @book = params.require(:book).permit(:book_id, :user_id)
  end  
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    binding.pry
    @messages = Message.where(user_id: current_user.id)
  end  

  def create 
    @book = Book.find(params[:book_id])
    @message = @book.messages.create(message_params)
    redirect_to "/books/#{@book.book_id}"
  end  

  def show
    @message = Message.find(params[:id])
    @book = Book.find(@message.book_id)
  end   

  def edit
    @message = Message.find(params[:id])
  end
  
  def update
    @message = Message.find(params[:id])
    @book = Book.find(@message.book_id)
    @message.update(title: message_params["title"],review: message_params["review"])
    redirect_to "/books/#{@book.book_id}"
  end  

  def destroy
    @message = Message.destroy(params[:id])
    @book = Book.find(@message.book_id)
    redirect_to "/books/#{@book.book_id}"
  end  

  private
  def message_params
    if current_user.try(:id)
      params["message"]["name"] = current_user.name
      params["message"]["user_id"] = current_user.id
    else
      params["message"]["name"] = "Guest"
      params["message"]["user_id"] = "Guest"
    end  
    params["message"]["title"] = params["message"]["title"] || params["title"] || params["message_title"]
    params["message"]["book_id"] = params["book_id"] || params["message_book_id"].keys[0] 
    @message = params.require(:message).permit(:title, :review, :user_id, :book_id, :name)
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:name], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to "/books"
    else
      flash[:alert] = "There was a problem loggin you in."
      redirect_to log_in_path
    end    
  end 

  def destroy 
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end
  
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      
    else
      redirect_to "/users/new"
    end    
  end   

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/books"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."  
      redirect_to :back
    end  
  end 

  def edit
    @user = User.find(params[:id]);
  end

  def update
    @user = User.find(params[:id]);
    @user.update(user_params)
    redirect_to "/users/#{@user[:id]}"
  end  

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end

  def user_edit_params
    params.require(:user).permit()
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.erb
<div class="space-8 container">
  <%= form_for @book do |f| %>
    Title: <%= f.text_field :title %>

    <%= f.submit %>
  <% end %>
</div>

app/views/books/index.erb
<div class="col-md-12 space-8">
</div>

<div class="row">
  <div class="col-md-4" >
  </div>
  <div class="col-md-4 space-4-bot">
    <h3 class="centered">Search For Books</h3>
    <form class="search-div"> 
      <div class="input-group search-div">
        <span class="input-group-btn">
          <button class="btn btn-primary" type="button">Search</button>
        </span>
        <input type="text" id="searchBox" name="searchBox" class="form-control search" placeholder="Search for Books...">
      </div>
    </form>  
    
  </div>
  <div class="col-md-1">
    <input type="hidden">
  </div>
</div>

<div class="container main-back">
  <div class="main">
    
  </div>
</div>

<script id="book-template" type="text/x-handlebars-template">
  <div class="entry">
    {{#each this.books}}
      <div class="col-md-2 even-div">
        <a href="/books/{{id}}" class="show-book">
          <div class="overlay-wrapper">
            <span class="focus-overlay"></span>
            <img class="book-shadow" src={{img}} height="210" width="160">
            <input type="hidden" value="{{el}}" class="bookEl">
          </div>
        </a>  
        <div class="book-info">
          <a href="/books/{{id}}" class="show-book">
            <div>
              <p class="title">{{dispTitle}}</p>
              <input type="hidden" value="{{el}}" class="bookEl">
            </div>  
          </a>
          <a href="/books/{{id}}" class="show-book">
            <div>
              <p class="authors">{{authors}}</p>
              <input type="hidden" value="{{el}}" class="bookEl">
            </div>  
          </a>
          <% if current_user %>   
            <p class="{{id}}">
              <a class="addBook">Add To Favorites
                <input type="hidden" value="<%= current_user.id %>" class="userId">
                <input type="hidden" value="{{el}}" class="bookEl">
              </a>
            </p>
          <% end %>  
        </div>  
      </div>
    {{/each}}
  </div>
</script>

app/views/books/show.erb
<div class="space-8 container book-show">
  <div class="col-md-12">
    <h2 class="bookShowTitle"></h2>
  </div>  

  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6 space-6-bot">
      <div class="row space-1-top">
        <div class="col-md-4 bookShowImg"></div>
        <div class="col-md-8">
          <div class="col-md-12">
            <div class="col-md-5 size-2 bookShowRating"></div>
            <div class="col-md-2"></div>
            <div class="col-md-5 lose-5-top bookShowLink"></div>
          </div>
          <div class="col-md-12">
            <p class="col-md-12 space-1-top bookShowAuthors"></p>
          </div>
          <div class="col-md-12">
            <p class="book-desc bookShowDesc"></p>
          </div>  
        </div>  
      </div>
      <div class="col-md-12">
        <% if current_user %>
          <div class="addRating">
            Rate This Book! 
            <input type="radio" name="rating" value="1">1
            <input type="radio" name="rating" value="2">2
            <input type="radio" name="rating" value="3">3
            <input type="radio" name="rating" value="4">4
            <input type="radio" name="rating" value="5">5
            <input type="submit" class="btn btn-sm ratingSubmit">
          </div>
        <% end %>  
        <div class="bookHiddenRating"></div>
      </div>

      <%= form_tag("/books/#{@book.id}/messages", method:"post", class: "space-2-top") do %>
        <%= text_field_tag :message_title, :title, value: "", placeholder:"Review Title", class:'form-control' %>
        <%= text_area :message, :review, placeholder:"Enter Review...",class:'form-control' %>
          <%= hidden_field :message_book_id, @book.book_id %>
          <%= hidden_field :message_user_id, @book.user_id %>

        <%= submit_tag("Create Review",class:"form-control btn-primary") %>
      <% end %><br>   
        
    </div> 
    <div class="col-md-3">
    </div> 
  </div>

  <div class="row">    
    <div class="col-md-3">
    </div>  
    <div class="col-md-6 min-height-5">  
      <h2>Reviews</h2>
       <% if @book.try(:messages) %>
        <% @book.messages.each do |message| %>
          <div class="col-md-12 border-grey">
            User: <a href="/books/<%= @book.id %>/messages/<%= message.id %>"><%= message.name %></a><br>
            Title: <a href="/books/<%= @book.id %>/messages/<%= message.id %>"><%= message.title %></a><br>
            Review: <a href="/books/<%= @book.id %>/messages/<%= message.id %>"><%= message.review %></a><br>
          </div>  
        <% end %>  
      <% else %>
      <% end %>
    </div>
    <div class="col-md-3">
    </div>  
  </div>  
</div>

<script>
  paramsCheck();
  descExpand();
  descContract();
</script>

app/views/landing/index.erb
<div class="row space-top-6 about-first">
  <div class="about-first-img">
  </div>
  <div class="col-xs-12 dark-overlay">
    <div class="container vert-center">
      <h1 class="centered">Find the right book for you.</h1>
      <h2 class="sub-header">Millions of books are available at your fingertips.</h2>
    </div>
  </div>
</div>  

<div class="row about-second">
  <div class="col-xs-12">
    <div class="container">
      <h2 class="centered space-top-8">Read It? Provides Several Helpful Features.</h2>
      <div class="row space-top-8">
        <div class="col-xs-4">
          <div class="round-border">
            <span class="helper"></span><img class="about-img" src="http://books.google.com/books/content?id=ohZ1wcYifLsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api">
          </div>
        </div>
        <div class="col-xs-4">
          <div class="round-border">
            <span class="helper"></span><img class="about-img" src="http://books.google.com/books/content?id=nv9lZM_0RI4C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api">   
          </div>
        </div>
        <div class="col-xs-4">
          <div class="round-border">
            <span class="helper"></span><img class="about-img" src="http://books.google.com/books/content?id=0cH0AAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api">
          </div>
        </div>
      </div>

      <div class="row about-second-details space-top-4">
        <div class="col-xs-4 border-right">
          <h3 class="about-second-title">Generous Collection of Books.</h3>
          <ul>
            <li>Search through Google's database of books.</li>
            <li>If you find something interesting, click the link to read it for free!</li>
          </ul>
        </div>
        <div class="col-xs-4 border-right"> 
          <h3>Add Your Favorites.</h3>
          <ul>
            <li>See something you like? Add it to your personal collection</li>
            <li>After creating an account you can create your own library!</li>
          </ul>
        </div>
        <div class="col-xs-4">          
          <h3>Write Your Own Reviews!</h3>
          <ul>
            <li>If you've had a powerful experience with a book, let others know.</li>
            <li>Read reviews to see which book is right for you.</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Read It?</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css"> 
  <link href='http://fonts.googleapis.com/css?family=PT+Sans|Roboto' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <h1><a href="/books" class="homeLink">Read It?</a></h1>     
  </div> 
  <div id="navbar" class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><a href="/landing" class="about">About</a></li>
    </ul>  
    <% if current_user %>
      <div class="navbar-form navbar-right">
        <%= link_to "Welcome, #{current_user.name}!", user_messages_path(current_user.id), class: "navbar-brand" %>
        <%= link_to "Sign Out", log_out_path, class: "btn btn-success" %>
      </div>  
    <% else %>   
      <%= form_tag log_in_path, class: "navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :name, nil, placeholder: "Username", class: "form-control" %>
        </div>  
        <div class="form-group">
          <%= password_field_tag :password, nil, placeholder: "Password", class: "form-control" %>
        </div>  
          <%= submit_tag "Log in", class: "btn-success btn" %> 
          <%= link_to "Sign Up", users_path, class: "btn btn-primary" %>
       <% end %> 
    <% end %>
  </div>
</div>
</nav>

<%= yield %>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
<script>
  API.getAll(getBooks,18);
</script>
</body>
</html>

<%= stylesheet_link_tag    params[:controller], media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag params[:controller], "data-turbolinks-track" => true %>

app/views/messages/index.erb
<div class="space-8 container">  
  <% if current_user.favorites.empty? && @messages.empty? %>
    <h3 class = "centered">You haven't added any favorites or reviews</h3>
  <% else %>  
    <div class="row">
      <% if !current_user.favorites.empty? %>
        <div class="row">
          <div class="col-md-12">
            <h2>Favorites</h2>
          </div>  
        </div>
        <div class="col-md-12 grey-back">
          <div class="centered">    
            <% current_user.favorites.each do |book| %>
              <div class="col-md-2 user-book-back">
                <div class="overlay-wrapper">
                  <a href="/books/<%= book.book_id %>">
                    <span class="focus-overlay"></span>
                    <img src="<%= book.img %>" height="200" width="150">
                  </a>
                </div>           
                <a href="/books/<%= book.book_id %>" class="show-book">
                  <p class="title"><%= book.title %></p>
                </a>  
              </div>
            <% end %>
          </div>  
        </div> 
      <% else %>
        <div>
          <h4 class="centered">You haven't added any favorites yet!</h4>
        </div>  
      <% end %>   
    </div>

    <div class="row">
      <% if !@messages.empty? %>
        <div class="row">
          <div class="col-md-12">
            <h2>My Reviews</h2>
          </div>
        </div>
        <div class="col-md-3">
        </div>
        <div class="col-md-6 grey-back min-height-7">
          <% @messages.each do |message| %>
            <div class="user_mes border-grey">
              Book: <a href="/users/<%= message.user_id %>/messages/<%= message.id %>"><%= message.book_title %></a><br>
              Title: <a href="/users/<%= message.user_id %>/messages/<%= message.id %>"><%= message.title %></a><br>
              Review: <a href="/users/<%= message.user_id %>/messages/<%= message.id %>"><%= message.review %></a><br>
            </div>  
          <% end %>      
        </div>
      <% else %>
        <h4 class="centered">You haven't added any reviews yet!</h4>
      <% end %>           
    </div> 
  <% end %>
</div>     
 

app/views/messages/show.erb
<div class="space-8 container">
  <div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
      <h2><%= @book.title %></h2><br>
      


      <%= form_for @message, url:book_message_path(@message.book_id,@message.id) do |f| %>
        <%= f.text_field :title, class:"form-control" %>
        <%= f.text_field :review, class:"form-control" %>
        <%= f.hidden_field :book_id, :value => @message.id %>

        <div class="col-md-6 space-2-top">
          <%= f.submit 'Edit Message',class:"btn-primary form-control" %>
        </div>  
      <% end %>  
      <div class="col-md-6 space-2-top">
        <%= link_to "Delete", book_message_path(@message.book_id,@message.id), method: :delete,class:"btn-danger btn form-control" %>
      </div>
      
    </div>
    <div class="col-md-3">
    </div>  
  </div>
  <div class="row">
    <div class="col-md-5">
    </div>
    <div class="col-md-2 space-2-top">
      
    </div>
    <div class="col-md-5">
    </div>
  </div>  
</div>

app/views/users/index.erb
      <%= current_user.name %>
      <a href="/users/<%= current_user.id %>/messages">My Reviews</a>

app/views/users/new.erb
<div class="space-8 container">
  <div class="col-md-3">
  </div>
  <div class="col-md-6">  
    <h2>Sign Up</h2>
    <%= form_for User.new do |f| %>
      <%= f.text_field :name,:placeholder => "Name",class:"form-control" %>
      <%= f.password_field :password,:placeholder => "Password",class:"form-control" %>
      <%= f.password_field :password_confirmation,:placeholder => "Confirm Password",class:"form-control" %>
      <%= f.submit "Sign Up",class:"form-control btn-primary" %>
    <% end %>
  </div>
  <div class="col-md-3">
  </div>  
</div>

app/views/users/show.erb
show.erb